# Generated by Django 2.2.5 on 2019-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('priority', models.PositiveSmallIntegerField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=1)),
                ('informations', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, null=True)),
                ('task_goal', models.CharField(blank=True, max_length=200)),
                ('task_priority', models.PositiveSmallIntegerField(blank=True)),
                ('task_reason', models.CharField(blank=True, max_length=200)),
                ('task_duration', models.IntegerField(default=1)),
                ('task_informations', models.CharField(blank=True, max_length=200)),
                ('task_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_tasks', models.ManyToManyField(to='tasks_app.Task')),
            ],
        ),
    ]
